### ISSUE TITLE
WoL compatibility

### ISSUE THREAD

**Issue by loup99** [rickinator9/WTWSMS#24]
This is the issue dedicated to achieving WoL compatibility, in order to make focuses usable.

**Comment by loup99** [comment]
I do not own WoL, so it would most likely be better for someone else to fix this.

**Comment by rquinio** [comment]
00_focuses.txt has been added via commit https://github.com/rickinator9/WTWSMS/commit/e356a58fc14a045f3c21409933eb50ceadade8a4, but it don't own WoL either, so can't test if that was enough.

**Comment by loup99** [comment]
Well, it seems like we are helped out: 
[QUOTE=secretfire;18654996]I noticed on Github you had a pull request on the WoL compatability, but none of you could test it because you didn't own WoL. I deleted my old mod folder and used your current Github build. You can choose a focus now, but none of the new options (choose to duel, seduce, etc.) work. I hope that helps.[/QUOTE]
So the focuses are available but none of the new options that are made in the new way of moddable diplomacy seem available.

**Comment by loup99** [comment]
Ok, it seems like they work, but with bugged events firing multiple times.

**Comment by rquinio** [comment]
I'm going to do a diff with vanilla 2.3 and check nothing is missing.

**Comment by rquinio** [comment]
I've merged some changes from vanilla 2.3 with commits https://github.com/rickinator9/WTWSMS/commit/9e011d9f182d266984c23ef71e46bfb17f7ecf7e https://github.com/rickinator9/WTWSMS/commit/18342c0e14027f2b84f14223447da73a26df3d39. Also some trait icons were missing https://github.com/rickinator9/WTWSMS/commit/83892dce99f243b75b9d396b74a978e313bb242d

I can't test properly without WoL, but I don't see why it wouldn't work properly now !

**Comment by rquinio** [comment]
According to Voltage video (https://www.youtube.com/watch?v=RzD3bvmcU8A), WoL works, so I'm closing the issue !
