### ISSUE TITLE
Choose starting era window

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#25]
Currently there is CTD when selecting an era (because obviously vanilla eras history is not covered by the mod).

I've started modding the window in the same way as AGoT mod:
- Remove the 2 first eras, as they are hardcoded to be DLC-locked.
- Use the 3 last eras to highlight the top 3 bookmarks.

**Comment by loup99** [comment]
Good, this had to be done. For the main bookmarks: I suggest having the 480 one and Rise of Islam. Unsure on the third one though.

**Comment by rquinio** [comment]
@loup99 I don't see the Rise of Islam bookmark in bookmarks.txt.

Do you prefer:
1) to show only BM_THE_OLDER_GODS (recommended one) for now to direct people to this bookmark only ?
2) or I pick 3 bookmarks (ex: BM_LITTLE_AUGUSTUS / BM_THE_OLDER_GODS / BM_FRANKISH_STEEL) for now ?

In any case, this can easily be changed later.
In the future, some text for 6 first characters of the 3 bookmarks (with key ERA_CHAR_INFO_<chararcter_id>) will need to be added for the 3 bookmarks.

**Comment by rquinio** [comment]
I did a compromise, putting the 3 eras, but using a custom gfx to highlight the bookmark.
Let me know what you think, I can still tweak things.
![eras](https://cloud.githubusercontent.com/assets/1886883/5603937/29c42152-939d-11e4-9df9-d4050d3d168a.jpg)

**Comment by loup99** [comment]
This is good, but for later Frankish Steel will have to be changed.

**Comment by loup99** [comment]
DC123456789 on the forums (dev for The Winter King) sugested that we could center the bookmaks, which is possible according to him. Could you do it?

**Comment by rquinio** [comment]
Sure, I'll have a look ! I was afraid that the sliding animation would be hardcoded so didn't try messing with the coordinates of the eras :)

**Comment by rquinio** [comment]
I propose to close this for now. 
Once the 3 final bookmark exist, description of characters can be added.
