### ISSUE TITLE
CoA and Flags issue

### ISSUE THREAD

**Issue by loup99** [rickinator9/WTWSMS#26]
This is the issue dedicated to the buggy flags and CoA in the 0.9.3.1. Romulien made some twaeks to flags previouly, but they are still (for me atleast) bugged. We do have a "clue" that i received:

[QUOTE=Fexn]However, I was poking around the flagfiles that is created in C:\Users\Usernmame\Documents\Paradox Interactive\Crusader Kings II\WTWSMS\gfx\flags and comparing it with the actual flag files (flagfiles_0 to be precise) and noticed that if you look the c_philippopolis coat of arms is duplicated, appearing once at the end of the fifth row and once again at the beginning of the sixth row, so it then puts all the other flags off by one. I have done literally no modding work at all, but I got counting and noticed that pattern. .[/QUOTE]

**Comment by rquinio** [comment]
The black dynasty coat of arms issue was fixed for me after commit https://github.com/rickinator9/WTWSMS/commit/6bb673017dc051e0398122bc8adfbe8b89790f0b, both a bookmark date and few years later with generated characters.

Do you still see black dynasties coa, and if yes for which religion ?

**Comment by loup99** [comment]
No, I do no longer see any black dynasties CoA, but the flag issue remains for Christian realms. I think the CoA issue also included some CoA:s being meleed around in the east.

**Comment by rquinio** [comment]
Ok I understand the problem now: all the flags are shifted by one in order they appear in landed_titles.txt. So for instance. c_ile_de_france has flag of c_vexin, c_vexin has flag of c_arques, etc.
c_philippopolis.

**Comment by rquinio** [comment]
Ok, validator complains about missing flag c_norrbotten.tga (love this tool !) and that solves the issue indeed.

**Comment by loup99** [comment]
Oh, I caused that issue.

**Comment by loup99** [comment]
Woops. I didn't know that avoiding to add flags caused huge issues. :stuck_out_tongue:

**Comment by loup99** [comment]
I will close this down, as you fixed it.
