### ISSUE TITLE
Remove duplicated gfx assets from vanilla

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#27]
Is there any reason for duplicated gfx assets from vanilla (interface, traits, event_pictures, ambitions) in the mod ?
Their respective folders (gfx/interface, gfx/event_pictures, gfx/traits, gfx/ambitions) are not "replace_path", so I think there is no need to duplicate.
It should reduce the mod size significantly.

**Comment by loup99** [comment]
There is no reason for it, but I had started removing stuff. VIET has added some, but the duplicate is unecessary.

**Comment by rquinio** [comment]
Ok I'll do a binary diff, and remove the assets that are duplicate from vanilla.
