### ISSUE TITLE
Typo: semetic_pagan vs semitic_pagan

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#32]
Both keys are used, causing issues with missing holy sites and reformed religion.
Do you confirm the proper name should be sem**i**tic_pagan as in "Sem**i**tic religion" ?
I think it may have come from some confusion with Kemetic religion.

**Comment by loup99** [comment]
Yes, semitic is what is meant. It might have been between Zusk or Enlil.
