### ISSUE TITLE
Broken adopt_feudalism decision 

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#34]
I still reproduce the issue with [adopt_feudalism] (https://github.com/rickinator9/WTWSMS/blob/master/WTWSMS/decisions/realm_decisions.txt#L1675), the allow tooltip shows:
 - (X) Capital:
  - (*) Government is Tribal
  - (X) Have a Stone Hilfort in --

even when there is a Stone Hilfort in the capital !

Issue is systematic for all tribal rulers, so it's not an issue with barony badly linked to county.
Decision code is identical to vanilla and in vanilla barony name displays fine in place of ---.

Any ideas welcomed !

**Comment by loup99** [comment]
Is there some event or new triggered mechanic linked to it?

**Comment by rquinio** [comment]
Solved, seemed to be a scope issue (holding scope vs province scope)
Strangely in vanilla, holding triggers/effects like has_building seem to work on province scope...weird !

**Comment by loup99** [comment]
Just a sidenote, other mods had this isue too, so it must be something from PDS
