### ISSUE TITLE
Missing/bad Localizations

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#35]
Issue to regroup missing or bad English localizations

TODO:
N/A

FIXED:
- gaelic
- k_dal_riata 
- k_caucasian_albania and d_caucasian_albania
- ct_culture_group_roman_1_desc
- neoplatonist, neoplatonist_desc, d_platonic_academy
- Capitalize "Georgian orthodox church"
- Remove override "My Religion" vs vanilla "My Religion Group"
- PROV1611
- central_african_pagan_reformed
- central_african_pagan_reforme_DESC
- create_valentinian_patriarchy + decription
- convert_to_spouse_nicene
- b_bzaya
- b_kkesfix
- b_fararah
- monatist
- monatist_DESC
- Attila the Hun spelled "Atilla"
- Roman Republic spelled "repubic"
- Legions (ex: d_legio_i_gallaecia)
- Organize legion decisions (ex: organize_legio_i_gallaecia)
- PROV1608
- PROV1609
- convert_to_spouse_xxx_DESC (islamic, ....)
- organize_legio_xxx_DESC

**Comment by rquinio** [comment]
I've fixed a few via commit https://github.com/rickinator9/WTWSMS/commit/8bb73da614ce201f66ebf88b7522ebef08c16fce

**Comment by rquinio** [comment]
I've fixed the one I could.
For the remaining ones, I'm lacking geographical/historical knowledge to put something relevant :)

**Comment by loup99** [comment]
I can look at it, except for the issues that are from Enlil/Zusk and require detailed knowledge on those weird heresies. :stuck_out_tongue:

**Comment by rquinio** [comment]
All issues fixed.
