### ISSUE TITLE
Improve mod maintainability and compatibility

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#36]
Whenever vanilla loads from a directory and no file in this directory needs to be removed from vanilla:
- try to extract the new stuff (events, decisions, ...) from vanilla files to a file with WtWSMS_ prefix.
- remove the file in case it is identical to vanilla
- remove the replace_path in .mod to allow mod + vanilla folders to merge on loading.

This would:
- reduce the amount of files to merge on new vanilla patch
- allow mini-mods that only add new stuff without altering files to be compatible with WtWSMS.

**Comment by rquinio** [comment]
I already did a few things with commit https://github.com/rickinator9/WTWSMS/commit/9e011d9f182d266984c23ef71e46bfb17f7ecf7e

**Comment by loup99** [comment]
Yes, this was what I did with the localisation, it is a lot more easier to maintain and to translate.

**Comment by rquinio** [comment]
True, I'm taking care of it for AncientReligions too: https://github.com/xirsoi/ancientreligions/pull/5

**Comment by loup99** [comment]
That is great, and I was epecially confused by what files belonged to what mod after Ancient Religions integration. VIET has been a lot more consistent with it.

**Comment by loup99** [comment]
What difftool are you using though? WinMerge is probaby simpler, it work with everything.

**Comment by rquinio** [comment]
I don't know WinMerge, but I'm using BeyondCompare, for its 3-way merge capability. I've discovered it's also quite powerful with .csv files, as it lists keys alphabetically rather than order in the file.

**Comment by rquinio** [comment]
I think most of the maintainability issues are solved !
