### ISSUE TITLE
Reformed pagans can't ask religious conversion

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#38]
Reformed pagans (germanic_pagan_reformed, baltic_pagan_reformed, ...) see the demand conversion diplomatic action, but even with +100 opinion, the character never agrees !

There is no such issue with Nicene, character agrees if opinion > +35.
Since it's an hardcoded diplomatic action, I'm not sure what's happening here.
Also tested in vanilla 2.3 with norse_pagan_reformed, there is no such issue.

**Comment by rquinio** [comment]
Actually seems to happen for all characters, not just (reformed) pagans.

**Comment by loup99** [comment]
Yes, I had this issue too, I could not force a prisoner to convert. Not sure what is behind it though.

**Comment by rquinio** [comment]
Maybe @EmperorEnlil or other devs remember when it starting to be bugged and what was changed at that time...
Otherwise a workaround could be to re-code completely the "demand religious conversion" action as a targeted decision, and set DEMAND_RELIGIOUS_CONVERSION_INTERACTION_ENABLED = 0.
It would allow some more control on which religions should be more resistant. But the tweak is getting the modifiers right for the A.I ...
Maybe @EmperorEnlil or other devs remember when it starting to be bugged and what was changed at that time...
Otherwise a workaround could be to re-code completely the "demand religious conversion" action as a targeted decision, and set DEMAND_RELIGIOUS_CONVERSION_INTERACTION_ENABLED = 0.
It would allow some more control on which religions should be more resistant. But the tweak is getting the modifiers right for the A.I ...

**Comment by loup99** [comment]
It started bugging with the WoL patch/official release as far as I know. In 2.2.1, it worked.

**Comment by loup99** [comment]
If the recoding is the best option, do it as we kind of needed more control anyway.

**Comment by rquinio** [comment]
Ok, got a working targeted decision !
For now the AI should do it systematically, if target meets the requirements.

**Comment by rquinio** [comment]
After testing the AI behavior, I had to split decisions in 2: one for courtier and one for vassals.
This is because there is no ai_target_filter that is combination of home_court + direct vassals.

**Comment by loup99** [comment]
Does this mean the interface for diplomatic actions now have two identical "Demand Conversion"-buttons? Anyway, it could potentially be used anyways, so no problems.

**Comment by rquinio** [comment]
Nope, only 1 appears at any given time as they have different potentials (one for rulers, one for unlanded) ;)

**Comment by loup99** [comment]
I know you finished this and recoded it, but what about the invitation to court that now seems to be buggy aswell? Do you think it is related to this issue as it bahaves in the same way?

**Comment by rquinio** [comment]
Funny thing: now the vanilla "Demand religious conversion" diplomacy is working again -_-'
Must have been the side effect of some other fixes. So I'll disable the targeted decisions for now, and fallback to vanilla action.

Regarding the AI reasoning not appearing for diplomatic actions, I still reproduce it, so that's a different cause. I've opened a separate issue #53 for this.

**Comment by loup99** [comment]
Will close this then as it works.
