### ISSUE TITLE
CoA patterns

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#39]
CoA patterns for some religions(jewish, hypsistarians, expanded zoro, all those of the size of vanilla indian, also edited christians ones to remove period inappropriate elements) courtesy of bontanel
http://www.mediafire.com/download/jdbe4a71yro6jvo/CoAPattern.rar

**Comment by rquinio** [comment]
Which template & colors should I use as basis for Hypsistarian CoA ?

**Comment by rquinio** [comment]
New patterns provided by @bontanel to be integrated:
http://www.mediafire.com/download/fyjq8k5np73ffv1/New_CoA.rar

**Comment by rquinio** [comment]
Some new CoA for zunists, dravidan pagans, neoplatonists(as well as cybelians), ashurists and kemetics(as well as manudlists). http://www.mediafire.com/download/ci11x91diru77t3/NewCoA.rar

**Comment by rquinio** [comment]
I've noticed that the county/barony flags in Arabia were often generic ones:

![genericflags1](https://cloud.githubusercontent.com/assets/1886883/5888059/b53a58ec-a3f0-11e4-85b9-ecbba1f8af44.jpg)
![genericflags2](https://cloud.githubusercontent.com/assets/1886883/5888061/c12626a4-a3f0-11e4-8650-11cf2d1b7b35.jpg)

Any idea what is causing this ?

**Comment by loup99** [comment]
Enlil had issues with this a lot earlier, and complained to Zusk. I believe he fixed it, but there was a problem with his patterns.

**Comment by loup99** [comment]
Enlil complained about the CoA patterns in Arabia to Zusk previously, not sure if he fixed it or how it was fixed.

**Comment by rquinio** [comment]
Ok so it's simply because the flags are like that in gfx/flags (d_azal.tga, c_ma_bar.tga etc.) :-)
I guess they are just placeholders to avoid shifting/messing the other flags.

**Comment by rquinio** [comment]
Also jewish_group and pagan_group religions have has_coa_on_barony_only = yes, so no random flags are generated, and it uses the one from gfx/flags.
Can't set it to "no" either, because it would generate random flags for ALL Pagans (like it does for Muslims), as it's set a religion group level.

**Comment by rquinio** [comment]
I'll close this as initial issue is resolved.
