### ISSUE TITLE
Muhammed Showed as a Normal Character

### ISSUE THREAD

**Issue by loup99** [rickinator9/WTWSMS#45]
This is a top priority issue. Hopefully it has not offended anyone...

**Comment by rquinio** [comment]
In vanilla it's occluded=yes in character history that does the trick.
It's missing in zusk_event.51 (if it works in create_character command)

**Comment by rquinio** [comment]
Trying to test the fix by reducing the MTTH to 1 day and changing year to 480.

**Comment by rquinio** [comment]
I've reproduced by changing the province_event into a character_event and firing it via console.
occluded=yes doesn't seem to work in create_character command...
Has it ever worked ? I see Zusk also worked on a specific ethnicity muhammadgfx too.

**Comment by rquinio** [comment]
Fixed by using set_graphical_culture = muhammad, whose graphical_culture is muhammadgfx.
I'm not sure of the impacts in case of children: it may be needed to reset their graphical_culture ?

**Comment by zajaxz123** [comment]
Can't you make the graphical culture count as arab_gfx or what is required
for purposes of inheritance?

**Comment by loup99** [comment]
not sure if it worked previously, Zusk handleed that, and I was not too much involved, only Enlil and Zusk have played that far.

**Comment by rquinio** [comment]
I've added an event to set graphical_culture of any children with muhammadgfx to arabicgfx.
Also added missing education/personality traits based on vanilla.

**Comment by loup99** [comment]
OK, closed this then. The general Rise of Islam issue can serve for the other discussion considering ths subject.
