### ISSUE TITLE
Compatibility with vanilla 2.3.2

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#47]
Merging of vanilla 2.3.2 changes in copied files.

**Comment by loup99** [comment]
You do it? OK, great. I do however only plan to make a new release next week, as I has some things I wanted to look at before.

**Comment by rquinio** [comment]
Ok, merge was very small, as duplicated vanilla files were removed :)
Anyway, I don't think there is any incompatibility between vanilla 2.3.1 and WtWSMS 0.9.4.

**Comment by loup99** [comment]
I have not compared the two, but no defines changed?

**Comment by rquinio** [comment]
No change in defines.lua :) Mainly localization, event and decision bugfix.
