### ISSUE TITLE
Portraits compatibility without sub-mods

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#49]
Now that I have better understanding of how vanilla loads stuff, I think there might be a way to do custom portraits using DLC assets, without using sub-mods. 
It relies on the fact *.gfx files are loaded __alphabetically__ by the engine (and last spriteType loaded overrides any previous with same name).
It needs to be tested, but the steps would be (for example for gothicgfx):
- create a file 00_portraits_norse.gfx with Norse DLC assets defaulting to western vanilla assets: 
```
spriteType = { 
name = "GFX_norse_male_base"
  texturefile = "gfx\\characters\\western_male\\western_male_base_1.dds"
  noOfFrames = 1
  norefcount = yes
}
```
- if Norse DLC is loaded, it will override these, via portraits_norse.gfx from dlc020:
```
spriteType = {
	name = "GFX_norse_male_base"
	texturefile = "gfx\\characters\\norse_male\\norse_male_base_1.dds"
	noOfFrames = 1
	norefcount = yes
}
```
- reference the assets from zz_portraits_gothic.gfx (not sure if zz_ prefix is actually needed)
```
name = "PORTRAIT_gothicgfx_male"
layer = {
  ...
  "GFX_norse_male_base:p2"
  ...
}
```
- remove `GFX_gothic_male_base` and similar definitions, as they are not actually used.

**Comment by loup99** [comment]
Oh, Ok, this would be good.

**Comment by rquinio** [comment]
Ok, tried it and that doesn't work... :/
It's because of the offsets: Celtic and Western portraits have different offsets, and Celtic Portraits DLC does not come with an offset file which resets them to 0x0, so it inherits vanilla ones with my method.
