### ISSUE TITLE
Pilgrimages

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#50]
The pilgrimage decision is available for catholic group, but does not trigger any event for the new religions.
I'll attach the SoA event chain with following pilgrimage sites:
- Nicene (and heresies): Jerusalem, Constantinople, Antioch, Rome
- Insular (and heresy): Canterbury only
- Georgian Orthodox: same as Orthodox

**Comment by loup99** [comment]
Ok, sounds good. Pilgrimages probably need tweaks too, but this will be sufficient for the time-being.

**Comment by loup99** [comment]
I'm adding the milestone, but no priority or need to rush this.

**Comment by rquinio** [comment]
Well, it's already done !
It's re-using the SoA events, so nothing special. For Canterbury, vanilla description was anachronic, so I put a simpler one. 
I've tested that Nicene and Insular ones are working fine.

**Comment by loup99** [comment]
Only one thing with this, isn't it possible to do something about the naming of Canterbury and have it adapt?

**Comment by rquinio** [comment]
Feel free to adapt, how was it called by Insular Christians ? :)

**Comment by loup99** [comment]
Well what I meant is to have a localisation that checks for the culture name od the province, but otherways the roman name was Durovernum Cantiacorum before it was abandoned. Really inapropriate holysite. :stuck_out_tongue: Will look into tat.

**Comment by rquinio** [comment]
Hmm, no I don't think it's possible to get the cultural name of an arbitrary title in localization via [ ] syntax.

**Comment by loup99** [comment]
Oh, I thought one could, must have been a confusion with another thing that was added.

Closing this for now, might reuse it later.
