### ISSUE TITLE
Weird Unit Models

### ISSUE THREAD

**Issue by loup99** [rickinator9/WTWSMS#52]
A lot of people across the forums have been reporting weird unit models, something that I suspect being related either to CM or an unit DLC. The description of the problem is the following: all of the units are the arabic ones/early eastern. If anyone would like to investigate further into this, feel free to do so, as I personally won't go too far with this due to lack of knowledge and prioritisation.

**Comment by loup99** [comment]
Oh, I almost forgot, this was a suggestion on how to fix the problem: http://forum.paradoxplaza.com/forum/showthread.php?827028-WtWSMS-Bug-Reports&p=18645932&viewfull=1#post18645932 :stuck_out_tongue:

**Comment by rquinio** [comment]
Ok, I see the issue now. 
Personal levies are OK, but vassal levies strangely use muslimgfx avatars, for instance heavy infantry:
![vassal_unit](https://cloud.githubusercontent.com/assets/1886883/5793132/659d530e-9f39-11e4-816b-324d222eace4.jpg)

**Comment by rquinio** [comment]
The proposed fix in the link above (addding avatars for southerngfx and occitangfx) won't solve it.
SWMH seem to have same vassal levies bug (but defaulting to westerngfx for all !): http://forum.paradoxplaza.com/forum/showthread.php?829574-Western-unit-models-for-Byzantine-cultures

**Comment by loup99** [comment]
Oh, Ok, then it is probably some issue from PDS or some new way of treating these. SWMH does though seem to be (in a bit of an evil wording as I know the dev team deals with a lot of stuff IRL) one of the most issue loaded HIP mods, so it might be due to their code. What is interesting however is that only SWMH has it, so it might be related to cultures or map modding somehow.

**Comment by rquinio** [comment]
HIP found out the cause was invalid titles referenced in history files.
I did a pass with the validator, and after some error fixing & cleanup, the bug is gone !
