### ISSUE TITLE
AI reasoning not appearing for diplomacy actions

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#53]
The AI reasoning tooltips are not appearing for diplomatic actions "Invite to Court", "Invite to Plot" etc. and characters never accept.

**Comment by rquinio** [comment]
SWMH had a similar issue recently (https://github.com/zijistark/SWMH/commit/f37eff17e6cb91b8299c1994c815a197c59eec6f). It seems to be linked to /landed_titles folder...

**Comment by rquinio** [comment]
Actually I don't reproduce the issue, I'm able to "Invite to Court" and "Invite to Plot" ! 
So maybe it was actually solved at the same time as the other strange bugs.

**Comment by loup99** [comment]
Ok, good. I could reproduce it previously, but no longer.
