### ISSUE TITLE
Samarobriva a part of Belgica

### ISSUE THREAD

**Issue by Pseudocatfish** [rickinator9/WTWSMS#54]
Can someone please move Samarobriva to Noviodunum and Lugdunensis? Thanks. (In fact, we probably should move all of the Norther part of soissons to lugdunensis to facilitate Clovis' invasion. What do you guys think?)

**Comment by loup99** [comment]
No, this is not happening.

**Comment by loup99** [comment]
Zusk mentioned looking at this, closing this issue.
