### ISSUE TITLE
Religious icons update

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#56]
Updated strip from bontanel: http://www.mediafire.com/download/0ntkz2ihd4droto/NewReligionIcons.rar
>I took a look to my old icons for religions and i decided to remake or tweak some of them. I also mad two new ones for kemetics(which was missing) and yazdanists(which aren't in the mod yet) so don't forget to change the number of frame in the interface files.

Also noticed some inconsistencies in heresy_icon for heresies at game start, causing issue if they become mainstream. For instance arian heresy icon is set to sanamahi one (Manipuran Paganism), rather than nicene heresy icon.

**Comment by rquinio** [comment]
Update is done !
Keeping this issue opened to track:
- Missing heresy icon for Hellenic (uses Aztec heresy icon for now)
- No specific icon for Celtic (uses vanilla generic pagan for now)

**Comment by loup99** [comment]
Great!

**Comment by rquinio** [comment]
Closing this one, as remaining points are now solved.
