### ISSUE TITLE
Roman province reconquest poping-up for early start dates

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#57]
There's a minor integration issue with ACR mod & LoR DLC: in earlier start dates (ex: 476), some provinces that were still fully controlled by Byzantine empire, are causing the "roman province reconquest" events to pop-up on game start (and thus free prestige gain).

There are global flags for each province (ex: syria_palaestina) to ensure events are only triggered once. I think the proper solution is for WtWSMS to set those flags on/off in province history files, based on actual dates these Roman provinces were lost.
This means:
- if starting in 476, event will never fire for Syria Palaestina (even if province is lost and then regained during the course of the game)
- if starting in 640, and Syria Palaestina is regained by Byzantine, event will fire properly.

Something completely dynamic would be better, but would also require complex events (NOT = { completly_controls = xxx } wouldn't work) to detect that such or such province has "fallen" etc. Not worth it, in my opinion.

I looked up the following dates:
- Provincia Syria Palaestina: 637 #Fall of Antioch
- Provincia Aegyptus: 637 #Fall of Khosrow
- Provincia Cyrenaica et Creta: 644 # Cyrenaica captured by Muslims
- Provincia Africa: 698 #Sack of Carthage
- Provincia Illyricum: 700 #Slavic invasions
- Provincia Italia: 568 #Lombard invasion
- Provincia Sicilia: 831 #Fall of Palermo
- Provincia Corsica et Sardinia: 831 #Lombard invasions in Corsica
- Provincia Viennensis: 475 #Goths independence recognized by Western Empire
- Provincia Gallia: 486 #Battle of Soissons
- Provincia Germania: 475 #Frankish Empire
- Provincia Britannia: 409 #Expulsion of Roman administration
- Provincia Hispania: 409 #Invasions
- Provincia Mauretania: 698 #Muslim conquests
- Provincia Mesopotamia: 637 #Muslim conquests
- Provincia Caledonia: 215 #Last roman campaign
- Provincia Hibernia: n/a

What do you think ?

**Comment by loup99** [comment]
I think we should add them to the history files, the player will anyway try to keep everything and if you loose them, it won't feel like a "reconquest" anyway.

**Comment by rquinio** [comment]
Ok I'll try this.

**Comment by rquinio** [comment]
It works quite well !
Also applied similar logic to Pentarchy events, that would otherwise fire at "Rule of Dukes" bookmark.
