### ISSUE TITLE
Non-ANSI characters in landed_titles.txt ?

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#58]
1) I'm having issues with some characters in landed_titles.txt, my editor doesn't want to save the file without changing encoding to UTF-8, for instance:
````
d_danube = {
  jute = Ðyenau
}
````
etc.
These names are also broken in game.

2) I've also noticed some names that are ANSI, but appear broken in game, for instance:
````
c_santiago = {
  visigothic =  AÃºrahji
}
````

**Comment by loup99** [comment]
Yes, I tried to change it previously, but I think the issue was with Enlil not using Norepad++

**Comment by rquinio** [comment]
Solved, solution with Notepad++:
- Open the file
- In Encoding menu, if encoded as UTF8 is selected, then select convert to ANSI
- Save the file
