### ISSUE TITLE
Sea raiding & Technology

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#60]
I've seen complaints that the mod was unplayable in some areas, due to constant see raids from pagans (cf https://www.youtube.com/watch?v=0VgIP3SKIgI)

Had a quick look at what would be causing that, and realized that no technology was actually applied.
(in defines.lua DONT_EXECUTE_TECH_BEFORE = 700)
Trying to change this to 400 crashes the mod on processing flags (or if set to 500, when switching to a later bookmark), so CTD is most certainly related to history files, but don't have a clue !

Also, would that be a viable solution to limit sea raiding via low shipbuilding technology, until the Viking age starts ?

**Comment by rquinio** [comment]
Got the technology to load, not sure what was wrong earlier....
I've used DONT_EXECUTE_TECH_BEFORE = 475

**Comment by loup99** [comment]
We want the sea raiding to be possible, kind of. The Vandals raided.

**Comment by loup99** [comment]
Although, the Vikings goinf to Africa is just crazy and unwanted. Really, only some realms should have acess to ships, but everbody should be able to raid.So your solution works, if certain realms get a higher technology/acess to ships.

**Comment by Ironmaggot** [comment]
Perhaps the raiders going berserk has something to do with low loot holdings everywhere except Mediterranean. Perhaps raiders are not raiding other pagans simply because the loot is so low that it is worthless and it is more worthwhile to sail down to the rich places.

**Comment by loup99** [comment]
True, but they should not have ships really at all and not raid with those. The only Germanic ones I see having ships are the Vandals and perhaps Wisigoths aswell as the people in Britain. No Germanics in Germany/Scandinvia should be able to send out ships until the Viking Age, and that is after the Germanic/Norse split.

**Comment by Ironmaggot** [comment]
Indeed, only ship type the northern pagans used during that dark time were simple rowing boats and I doubt that they were rowing very far with them. Crossing the Baltic Sea was doable and they did it with their rowing boats, but this kind of exception is probably not implementable - it is either full blown ships or no ship at all.

**Comment by rquinio** [comment]
Ok, I've tried something: https://github.com/rickinator9/WTWSMS/pull/65

**Comment by rquinio** [comment]
Closing as technology nerf was merged, feel free to re-open if you see issues.
