### ISSUE TITLE
Crash on day 2

### ISSUE THREAD

**Issue by Zusk** [rickinator9/WTWSMS#68]
![gifcam](https://cloud.githubusercontent.com/assets/10676712/6430037/f2a9e554-bfab-11e4-8dc0-c53ee7484273.gif)

Using the current github version of the mod causes a crash on day 2.

**Comment by loup99** [comment]
Does it systematically do this?

**Comment by Zusk** [comment]
It does this every time.

I have no tried to run the mod in the last, 15 or so days.

**Comment by loup99** [comment]
I have not tried the last version since I removed the agetraits, but that can't be the cause to the crash.

**Comment by rquinio** [comment]
I get the "usual" random crashes every few years/months (very variable), but no specific issue on day 2.
Check that your .mod file is up to date between git and mod folder.

**Comment by loup99** [comment]
[img]http://i.imgur.com/CDamzyW.png[/img]

Yeah, I just ran past that date with no problems, so the issue must be on your end. I did, however, encounter another issue, unrelated to that.

**Comment by rquinio** [comment]
Is that a broken/greyed province ?

**Comment by loup99** [comment]
It is, I mentioned it in the group too.

**Comment by Zusk** [comment]
I have double checked the .mod file and got the new one from Git. Its still causing crashes on day 2.

To be sure, I tried launching it without the event folder, its still crashing.

**Comment by loup99** [comment]
Have you made any uncommited changes to the Git? Are you on vesion 2.3.3? What is your checksum?

**Comment by Zusk** [comment]
2.3.3

YAUL is the checksum

**Comment by loup99** [comment]
And mine, on the same version, is ZJCB

**Comment by Zusk** [comment]
I have completely reinstalled CK2, verified the integrity of the cache and have the following DLC's used.

CK2 DLC:
All but Way of Life

Mods:
WTWSMS African Portraits
WTWSMS Celtic + Turkish Portraits
WTWSMS Norse Portraits
When the World Stopped Making Sense

This leads to the checksum being YAUL

**Comment by loup99** [comment]
This should nmot have an impact, but why ar you not using the Celtic Portraits module? 

And i just verified my cache and I also have all DLC's enabled except Wol, some music, CM Coat of Arms and Unit Packs. My checksum is the same: ZJCB

**Comment by Zusk** [comment]
I can attempt to run this through a alternative computer, see if that fixes it.

**Comment by Zusk** [comment]
Okay, I have just ran this on my other computer, straight clean install with no DLC.

The Checksum? DAHQ

**Comment by Zusk** [comment]
Okay, wiping out my documents/paradox interactive folder made the checksum on my old computer DAHQ as well.

I will try to insert the mod and see if this had fixed the issue. As DAHQ seems to be the official checksum of the most recent patch.
http://forum.paradoxplaza.com/forum/showthread.php?836328-Crusader-Kings-II-2.3.3-PATCH-RELEASED-Checksum-DAQH-NOT-for-problem-reports!

**Comment by Zusk** [comment]
Hazzah! The game has managed to get past day 2 running under the DAHQ checksum.

Now that I have gotten this sorted with, ill start to get to work importing those files I have been working on.

**Comment by rquinio** [comment]
I get ZJCB as well on last commit (just for info)
