### ISSUE TITLE
Blank events for one province minors

### ISSUE THREAD

**Issue by Zusk** [rickinator9/WTWSMS#72]
![mongrels](https://cloud.githubusercontent.com/assets/10676712/6496921/d1b3d87a-c28d-11e4-9acc-22ff9dfcad2c.png)

I think this might be related with the 'have somebody help sort out your holdings' event. Event id 108000

**Comment by Zusk** [comment]
Okay, its not council events, ill go through the list and see what it is!

**Comment by rquinio** [comment]
You could use [the validator](http://www.ckiiwiki.com/The_Validator), and checking for errors in event files. We're now below 100 errors on WtWSM_ events. Blank events are usually reported as "Invalid node xxx in scope yyy".

**Comment by Zusk** [comment]
I have, for testing purposes tried to launch the mod entirely without the event folder itself, this still gives the blank events.

The invalid nodes I can find with the validator are from vanilla events.

**Comment by Zusk** [comment]
I have attempted running this without the on_actions folder, to see if a invalid event was being triggered from on_actions. No dice.

**Comment by Zusk** [comment]
Decisions isn't doing it either

**Comment by Zusk** [comment]
Hazzah! It no longer fires if I don't run -any- vanilla events, it must be a event conflict somewhere with the vanilla files and this version.

Ill try to find it!

**Comment by Zusk** [comment]
Alright, this issue has been fixed!

**Comment by Zusk** [comment]
...Well, I -thought- at least. Turns out the conflict isn't just in achievement_events.txt but also plot_events.txt.

I got to scour through this one a bit for the fix, its a pretty big file,

**Comment by Zusk** [comment]
.....Welp, im stupid.

The issue was only caused by my local files, not a issue with the github at all.
Ill close this for now, at least I managed to speed up the mod a bit through the removal of those achievement checks :dancer:
