### ISSUE TITLE
Roman clothing from Silfae

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#73]
Some proposed Roman clothing from Silfae on the [forum](http://forum.paradoxplaza.com/forum/showthread.php?833456-WtWSMS-GFX-Art-Flags-Icons-Units-Holdings-Pictures-CoA-etc&p=18979843&viewfull=1#post18979843).

![promo](https://cloud.githubusercontent.com/assets/1886883/6515903/3cd12ab2-c38e-11e4-8276-ef9c0f11a565.jpg)

Seems really sweet. Removes all crowns, except for Imperator's laurels.
http://www.mediafire.com/download/h4q3pp18yb5111x/romans_ready.rar

**Comment by loup99** [comment]
Great! We should definetly use this!

**Comment by rquinio** [comment]
I'll take a shot at integrating this.
Since southerngfx is now used in vanilla by Iberian Portraits DLC, it's probably best to use a separate romangfx for Roman cultures.
However as eastern Romans uses byzantinegfx, this will only apply to western Romans.

**Comment by loup99** [comment]
Ok, do it seprate then. Those portraits really look good and will make me play romans. :stuck_out_tongue:

**Comment by rquinio** [comment]
Here's how romangfx looks:
![roman_portraits_diff](https://cloud.githubusercontent.com/assets/1886883/6542158/fbf9b6bc-c4f0-11e4-88d3-af2c43fdb182.jpg)
From left to right: Emperor Julius Nepos, Rex Syagrius of Soissons, a Praetorian, Imperatrix Juliana, a Gallo-Roman Legatus Augusti.

Any suggestions regarding beards for romangfx ?
My understanding is that until 200-300 A.D Romans didn't grow beards, but later they started copying Greeks.
However the Mediterranean beard feel more barbaric than Roman, so I'm inclined to put a hight modifier on no beard for romangfx in portrait_properties.

**Comment by loup99** [comment]
Looks good! Not sure for the beard, but didnt some roman people inspire themselves on barbarians too?

**Comment by rquinio** [comment]
Don't know, I'll do the pull request with current state, this can always be tweaked later !

**Comment by loup99** [comment]
Will close this for the moment, for any tweaks, re-open it.
