### ISSUE TITLE
Blank Aneb Province

### ISSUE THREAD

**Issue by Zusk** [rickinator9/WTWSMS#75]
![fixe](https://cloud.githubusercontent.com/assets/10676712/6523287/3a419e7a-c3a3-11e4-9e34-b010101b203b.png)

I didn't see a issue posted for this one yet, but I fixed the Blank Aneb that was in the dev version.
You will also notice that the african nations now have vassals! Ill incorporate all of that after I finish this batch of work I am working on.

**Comment by Zusk** [comment]
Just posting this here, this can be closed when people see that the issue has been resolved.

**Comment by loup99** [comment]
Zusk, we are going to split the African nations. Also, I'm closing this, as the best way of seeing what has been done or not is the changelog, and this issue can still be found for reference.

**Comment by rquinio** [comment]
But the issue is not fixed yet, right ?

**Comment by loup99** [comment]
No, not yet according to Zusk's message.

**Comment by Zusk** [comment]
Wait, splitting the african nations?

What does this mean? What is going to be the new setup?

**Comment by loup99** [comment]
Yes, Enlil stated previously that he was going to divide them, or internally make vassals (the latter is just wht you plan on doing). The issue with Enlil is that the GitHub does not work for him, so he can't do anything.

**Comment by Zusk** [comment]
This change is now implemented, and thus this can be closed.
