### ISSUE TITLE
Patch 2.3.4 compatibility

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#78]
There seem to be 2 conflicting files between master branch and new vanilla patch:
- 00_event_modifiers.txt (new modifiers for war focus strategist path)
- wol_business_events.txt  (some kind of scope fix between event WoL.10117 and WoL.10119)

**Comment by loup99** [comment]
OK, that won't be hard to fix then. I can merge those changes with WinMerge when I will have acess to the proper computer (this week-end)
