### ISSUE TITLE
Typos in religious_decisions

### ISSUE THREAD

**Issue by Moopli** [rickinator9/WTWSMS#79]
A couple of the heretical patriarch decisions don't give the new patriarch the correct religion and patriarchate.

[Example](https://github.com/rickinator9/WTWSMS/blob/master/WTWSMS/decisions/WtWSMS_religious_decisions.txt#L83).

**Comment by rquinio** [comment]
Nice spot.
I checked the whole file, there seemed to be only 2 typos on create_ebionites_patriarchy decision.
