### ISSUE TITLE
Mod installer for Windows 

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#80]
Lot of support goes to players with a bad mod installation, so let's make things easier with a little installer !
The steps of installer will be:
1) Delete previous mod files
2) Clean gfx cache
3) Install new mod files (mod folder and .mod)

NSIS (http://nsis.sourceforge.net) appears to be simple and customizable, so I'll add a script for it.

**Comment by rquinio** [comment]
Here is how it looks like:

![language](https://cloud.githubusercontent.com/assets/1886883/8159998/49e3e040-136c-11e5-8506-884d440af743.jpg)
![welcome](https://cloud.githubusercontent.com/assets/1886883/8160003/4e73643c-136c-11e5-9da8-4cdc62acfb35.jpg)
![directory](https://cloud.githubusercontent.com/assets/1886883/8160004/4fa92648-136c-11e5-9017-8143ef946268.jpg)
![install](https://cloud.githubusercontent.com/assets/1886883/8160005/50d60130-136c-11e5-8495-1774db7de3ca.jpg)
![finish](https://cloud.githubusercontent.com/assets/1886883/8160007/54186810-136c-11e5-96eb-370c54ea53e5.jpg)

**Comment by rquinio** [comment]
The CK2 default mod folder is prefilled, and the various texts can be adapted in the setup.nsi file.

To build the .exe:
1) Install Uniode NSIS 2.46.5 from https://code.google.com/p/unsis/downloads/list
2) Right-click the file setup.nsi in Git root directory, and select "Compile Uniode NSIS Script"
3) It compresses the files and generates WtWSMS-setup.exe in same directory (can then be renamed with version number)

With latest master commit, the resulting .exe size is 60Mo with default compression, similar to Github .zip download of 62 Mo.

**Comment by loup99** [comment]
This is really nice! I have been busy the two latest days so I had not checked this, but great work! Does it mean that we can use this for the older version too?

**Comment by loup99** [comment]
There is one thing though, that concerns me and that I had completely forgotten:

> Below are the rules you must follow if you want to Mention/Discuss/Plan or otherwise Market your User mod on our forums and or list it in the steam Workshop.

> 3) The User Mod will not distribute the EXE file.

**Comment by rquinio** [comment]
Thanks ! Feel free to adapt the text if needed.

I could create a branch for the older version on github and put the script there if needed. Depends if we will release a new version from master with 2.4 compatibility (are there some blocking bugs on master ?) or if we do the compatibility on the old version ?

Don't worry about it being an .exe, the rule applies only for the CK2.exe and our .exe will only contain mod files and no binaries from vanilla.

**Comment by loup99** [comment]
I do not think we will do compatbility from the old version (would be a step backwards, and if when 2.4 releases the issues with migration/rise of islam are still prsent, we can remove those), but I was mostly asking in order to be able to upload the current latest release version in an "installer-version", as I do not know when Enlil, Zusk and Erik W will be ready for releasing the next public version, and meanwhile people are downloading the current release.

**Comment by rquinio** [comment]
Sure, in fact all is needed is the .nsi file, so what you can do is:
1) Unzip WTWSMS-v.0.9.5.zip somewhere
2) Take the setup.nsi file from Git, and put it into the unzipped folder, at the same level as .mod files
3) Right-click setup.nsi and select "Compile Unicode NSIS Script"
4) Rename the output WtWSMS-setup.exe to something like WtWSMS-v.0.9.5-setup.exe

Btw, be careful when testing the installer: because of the symbolic links, it will overwrite any uncommitted stuff in git working directory. Best is to remove the links first (by deleting the folders with a link icon).

**Comment by loup99** [comment]
Thanks, will look into doing that and sharing the new installer! ::):

**Comment by rquinio** [comment]
I've updated the wiki page as well: http://www.ckiiwiki.com/When_The_World_Stopped_Making_Sense#Installation
This issue seems done, so closing it. Separate issues can be opened to track any bugs/improvements, once player start using it more widely.
