### ISSUE TITLE
Syntax error in definition.csv

### ISSUE THREAD

**Issue by Moopli** [rickinator9/WTWSMS#81]
Simple fix, remove double-quotes, because they are not necessary. Were they necessary, you would have to double-quote the whole entry, and escape each double-quote that appears within using *another* double-quote. Although CK2 doesn't *currently* seem to require csv files to follow rfc4180, github does, and it would display in a nice table format.

https://github.com/rickinator9/WTWSMS/blob/master/WTWSMS/map/definition.csv#L1472
https://www.ietf.org/rfc/rfc4180.txt

**Comment by rquinio** [comment]
I've yet to see a CK2 csv file display properly on Github. ^^
Even with fixing the illegal quotes and other column number mismatch, the error "No commas found in this CSV file "  remains, for instance:
* https://github.com/rickinator9/WTWSMS/blob/master/WTWSMS/localisation/WtWSMS_nicknames.csv
* https://github.com/rickinator9/WTWSMS/blob/master/WTWSMS/localisation/WtWSMS_wikipedia.csv

How to tell Github the separator is semi-column and not comma ?

**Comment by rquinio** [comment]
Seems Github viewer only supports comma (.csv) and tabs (.tsv) as separators...
So sadly nothing we can do for now.
