### ISSUE TITLE
Compatibility with patch 2.4.1 and 2.4.2

### ISSUE THREAD

**Issue by rquinio** [rickinator9/WTWSMS#82]
Issue to track compatibility and merging with vanilla patch 2.4.1.

**Comment by rquinio** [comment]
Patch is out, game won't even start with version of the mod ^^
I'm starting the merging, see how it goes.

**Comment by rquinio** [comment]
Merge of files is done and the mod is working again, yay !

Remaining work is to adapt the regions definition:
https://github.com/rickinator9/WTWSMS/blob/master/WTWSMS/map/geographical_region.txt
https://github.com/rickinator9/WTWSMS/blob/master/WTWSMS/map/island_region.txt
@EWattman you probably know the vanilla vs WtWSMS duchies / new islands better than me, feel free if you have time :p

**Comment by EWattman** [comment]
I won't have much time the coming week, but the weekend after this weekend I should have time to go over this

**Comment by rquinio** [comment]
I've noticed clicking the "Shattered Empire" bookmark in the era popup causes CTD (the other 2 bookmark work fine though). Not sure what's causing it, as issue doesn't occur when selecting bookmark from custom game setup...

**Comment by loup99** [comment]
To my understanding, this is achieved, so I'm closing this issue now.
